package ch.heig.dma.nearnote.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Represents a single note in the application.
 *
 * @property id The unique identifier for the note, auto-generated by Room.
 * @property title The title of the note. Defaults to an empty string.
 * @property text The main content/text of the note. Defaults to an empty string.
 * @property locationName A human-readable name or address for the note's location. Defaults to an empty string.
 * @property latitude The latitude of the note's location. Defaults to 0.0 (no location).
 * @property longitude The longitude of the note's location. Defaults to 0.0 (no location).
 * @property radius The radius in meters for geofencing around the note's location. Defaults to 100f.
 * @property isActive Indicates if the note (and its geofence) is currently active. Defaults to true.
 */
@Parcelize
@Entity(tableName="note")
data class Note(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String = "",
    val text: String = "",
    val locationName: String = "",
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val radius: Float = 100f,  // Rayon en mètres pour le géofencing
    val isActive: Boolean = true
): Parcelable {

    /**
     * Creates a new [Note] instance by copying the current note and updating specified fields.
     * If [loc] is null, location fields are reset to their defaults (no location).
     *
     * @param newTitle The new title for the note.
     * @param newText The new text content for the note.
     * @param loc An optional [Location] object. If provided, its details update the note's location.
     * @return A new [Note] instance with updated values.
     */
    fun updated(
        newTitle: String,
        newText: String,
        loc: Location?
    ) = copy(
        title = newTitle,
        text = newText,
        locationName = loc?.name.orEmpty(),
        latitude = loc?.lat ?: 0.0,
        longitude = loc?.lng ?: 0.0
    )
}